/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jijwa
 */
public class frmZirboinFinancialJW extends javax.swing.JFrame {
    
    /**
     * Creates new form frmZirboinFinancialJW  
     */
    public frmZirboinFinancialJW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnlOutput = new javax.swing.JPanel();
        lblDrobzitsHeader = new javax.swing.JLabel();
        lblClickwicksHeader = new javax.swing.JLabel();
        lblFrazointsHeader = new javax.swing.JLabel();
        lblBlointointsHeader = new javax.swing.JLabel();
        lblGazoontightsHeader = new javax.swing.JLabel();
        lblVrobitsHeader = new javax.swing.JLabel();
        lblClickwicks = new javax.swing.JLabel();
        lblFrazoints = new javax.swing.JLabel();
        lblDrobzits = new javax.swing.JLabel();
        lblGazoontights = new javax.swing.JLabel();
        lblVrobits = new javax.swing.JLabel();
        lblBlointoints = new javax.swing.JLabel();
        imgSpace = new javax.swing.JLabel();
        pnlInput = new javax.swing.JPanel();
        lblInst = new javax.swing.JLabel();
        txtVrobits = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblDrobzitsHeader.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblDrobzitsHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDrobzitsHeader.setText("Drobzits");

        lblClickwicksHeader.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblClickwicksHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClickwicksHeader.setText("Clickwicks");

        lblFrazointsHeader.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblFrazointsHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrazointsHeader.setText("Frazoints");

        lblBlointointsHeader.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblBlointointsHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlointointsHeader.setText("Blointoints");

        lblGazoontightsHeader.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblGazoontightsHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGazoontightsHeader.setText("Gazoontights");

        lblVrobitsHeader.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblVrobitsHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVrobitsHeader.setText("Vrobits");

        lblClickwicks.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        lblClickwicks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClickwicks.setText("0");

        lblFrazoints.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        lblFrazoints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrazoints.setText("0");

        lblDrobzits.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        lblDrobzits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDrobzits.setText("0");

        lblGazoontights.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        lblGazoontights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGazoontights.setText("0");

        lblVrobits.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        lblVrobits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVrobits.setText("0");

        lblBlointoints.setFont(new java.awt.Font("Bodoni MT Black", 0, 12)); // NOI18N
        lblBlointoints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlointoints.setText("0");

        javax.swing.GroupLayout pnlOutputLayout = new javax.swing.GroupLayout(pnlOutput);
        pnlOutput.setLayout(pnlOutputLayout);
        pnlOutputLayout.setHorizontalGroup(
            pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDrobzitsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrobzits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOutputLayout.createSequentialGroup()
                        .addComponent(lblClickwicks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGazoontights, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOutputLayout.createSequentialGroup()
                        .addComponent(lblClickwicksHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGazoontightsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOutputLayout.createSequentialGroup()
                        .addComponent(lblFrazoints, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBlointoints, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOutputLayout.createSequentialGroup()
                        .addComponent(lblFrazointsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBlointointsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVrobitsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlOutputLayout.setVerticalGroup(
            pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrobzitsHeader)
                    .addComponent(lblClickwicksHeader)
                    .addComponent(lblGazoontightsHeader)
                    .addComponent(lblFrazointsHeader)
                    .addComponent(lblBlointointsHeader)
                    .addComponent(lblVrobitsHeader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClickwicks, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFrazoints, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrobzits, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGazoontights, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBlointoints, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imgSpace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nightSky.jpg"))); // NOI18N
        imgSpace.setText("jLabel15");

        lblInst.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lblInst.setText("Input the number of Vrobits");

        txtVrobits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVrobitsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputLayout = new javax.swing.GroupLayout(pnlInput);
        pnlInput.setLayout(pnlInputLayout);
        pnlInputLayout.setHorizontalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInst, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlInputLayout.setVerticalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(imgSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(pnlInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imgSpace)
                .addGap(18, 18, 18)
                .addComponent(pnlOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVrobitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVrobitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVrobitsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // Variables
        int drobzits;
        int clickwicks;
        int gazoontights;
        int frazoints;
        int blointoints;
        int vrobits;
        
        // Constants
        final int DROBZIT_VALUE = 100000;
        final int CLICKWICK_VALUE = 50000;
        final int GAZOONTIGHT_VALUE = 10000;
        final int FRAZOINT_VALUE = 1000;
        final int BLOINTOINT_VALUE = 500;
        
        
        // Get number of Vrobits
        vrobits = Integer.parseInt(txtVrobits.getText());
        
        // Calculate the number of Drobzits
        drobzits = vrobits / DROBZIT_VALUE;
        vrobits = vrobits % DROBZIT_VALUE;
        
        // Calcualte the number of Clickwicks
        clickwicks = vrobits / CLICKWICK_VALUE;
        vrobits = vrobits % CLICKWICK_VALUE;
        
        // Calculate the number of Gazoontights
        gazoontights = vrobits / GAZOONTIGHT_VALUE;
        vrobits = vrobits % GAZOONTIGHT_VALUE;
        
        // Calcualte the number of Frazoints
        frazoints = vrobits / FRAZOINT_VALUE;
        vrobits = vrobits % FRAZOINT_VALUE;
        
        // Calcualte the number of Blointoints
        blointoints = vrobits / BLOINTOINT_VALUE;
        vrobits = vrobits % BLOINTOINT_VALUE;
        
        // Output the results
        lblDrobzits.setText(String.valueOf(drobzits));
        lblClickwicks.setText(String.valueOf(clickwicks));
        lblGazoontights.setText(String.valueOf(gazoontights));
        lblFrazoints.setText(String.valueOf(frazoints));
        lblBlointoints.setText(String.valueOf(blointoints));
        lblVrobits.setText(String.valueOf(vrobits));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmZirboinFinancialJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmZirboinFinancialJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmZirboinFinancialJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmZirboinFinancialJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmZirboinFinancialJW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgSpace;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBlointoints;
    private javax.swing.JLabel lblBlointointsHeader;
    private javax.swing.JLabel lblClickwicks;
    private javax.swing.JLabel lblClickwicksHeader;
    private javax.swing.JLabel lblDrobzits;
    private javax.swing.JLabel lblDrobzitsHeader;
    private javax.swing.JLabel lblFrazoints;
    private javax.swing.JLabel lblFrazointsHeader;
    private javax.swing.JLabel lblGazoontights;
    private javax.swing.JLabel lblGazoontightsHeader;
    private javax.swing.JLabel lblInst;
    private javax.swing.JLabel lblVrobits;
    private javax.swing.JLabel lblVrobitsHeader;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JPanel pnlOutput;
    private javax.swing.JTextField txtVrobits;
    // End of variables declaration//GEN-END:variables
}
