/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jijwa
 */
public class frmDoublesJW extends javax.swing.JFrame {
    
    // Global variables
    int round = 0;
    int totalScore = 0;
    int highScore = 0;
    int score = 0;
    
    
    // Methods
    
    /* rollDice
    
    This method rolls two dice and returns their values
    
    Parameters: none
    
    Returns: int []
    
    */
    public static int [] rollDice() {
        // Variables
        int [] rolls = new int [2];
        
        // Roll dice
        for (int j = 0; j < 2; j ++){
            rolls[j] = (int)Math.round(Math.random() * 5);
        }
        
        // Return dice rolls
        return rolls;
    }
   
    /* checkDoubles
    
    This method checks to see if two dice are doubles
    
    Parameters: int []
    
    Returns: boolean
    
    */
    public static boolean checkDoubles (int [] diceRolls) {
        // Check if the rolls are the same
        if (diceRolls[0] == diceRolls[1]) {
            return true;
        }
        return false;
        
    }
    
    /* endRound
    
    This method performs all the neccesary tasks to end a round
    
    Parameters: none
    
    Returns: none
    
    */
    public void endRound () { // Static wasn't included because it isn't compatible with global variables
        // reset the score
        score = 0;
        
        // Increase the round number
        round ++;
        
        // Disable the stop button so you can't stop before the dice have been rolled
        btnStop.setEnabled(false);

        // Check if the game is over
        if (round >= 3) {
            // Disable the go and stop buttons, enable the start button
            btnStart.setEnabled(true);
            btnGo.setEnabled(false);
            btnStop.setEnabled(false);

            // Reset the round
            round = 0;
        }
    }
    
    /* outputData
    
    This method outputs the score, high score, total score and the round number
    
    Parameters: none
    
    Returns: none
    
    */
    public void outputData () { // Static wasn't included because it isn't compatible with global variables
        // Output the stats
        lblScore.setText("Score: " + score);
        lblHighScore.setText("High Score: " + highScore);
        lblTotalScore.setText("Total Score: " + totalScore);
        lblRound.setText("Round: " + (round + 1) + "/3");
    }

    /* displayDiceFaces
    
    This method outputs the dice faces that have just been rolled
    
    Parameters: none
    
    Returns: none
    
    */
    public void displayDiceFaces (int [] rolls) { // Static wasn't included because it isn't compatible with global variables
        // Constants
        final String [] DICE_FACES = {"/dice1.png", "/dice2.png", "/dice3.png", "/dice4.png", "/dice5.png", "/dice6.png"};
        
        // Set the icons to the dice faces
        lblDice1.setIcon(new javax.swing.ImageIcon(getClass().getResource(DICE_FACES[rolls[0]])));
        lblDice2.setIcon(new javax.swing.ImageIcon(getClass().getResource(DICE_FACES[rolls[1]])));
    }

    
    /**
     * Creates new form frmDoublesJW
     */
    public frmDoublesJW() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblInst1 = new javax.swing.JLabel();
        lblInst2 = new javax.swing.JLabel();
        lblRound = new javax.swing.JLabel();
        lblHighScore = new javax.swing.JLabel();
        lblTotalScore = new javax.swing.JLabel();
        lblInst3 = new javax.swing.JLabel();
        pnlRound = new javax.swing.JPanel();
        lblScore = new javax.swing.JLabel();
        lblDice1 = new javax.swing.JLabel();
        lblDice2 = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doubles");

        lblTitle.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Doubles");

        lblInst1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblInst1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst1.setText("Roll the dice, every time you don't roll doubles, your points go up by the sum of the rolls!");

        lblInst2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblInst2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst2.setText("You can stop at any time, but if you roll doubles, you loose all the points gained in that round!");

        lblRound.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRound.setText("Round: 1/3");

        lblHighScore.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblHighScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHighScore.setText("High Score:");

        lblTotalScore.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblTotalScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalScore.setText("Total Score: ");

        lblInst3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblInst3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst3.setText("Play for three rounds, and see if you can set yourself a new high score!");

        pnlRound.setBackground(new java.awt.Color(255, 255, 255));
        pnlRound.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblScore.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("Score: 0");

        lblDice1.setBackground(new java.awt.Color(255, 255, 255));
        lblDice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice6.png"))); // NOI18N
        lblDice1.setText("jLabel2");
        lblDice1.setOpaque(true);

        lblDice2.setBackground(new java.awt.Color(255, 255, 255));
        lblDice2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice6.png"))); // NOI18N
        lblDice2.setText("jLabel2");
        lblDice2.setOpaque(true);

        btnGo.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnGo.setText("Keep going");
        btnGo.setEnabled(false);
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        btnStop.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnStop.setText("Stop");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRoundLayout = new javax.swing.GroupLayout(pnlRound);
        pnlRound.setLayout(pnlRoundLayout);
        pnlRoundLayout.setHorizontalGroup(
            pnlRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRoundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRoundLayout.createSequentialGroup()
                        .addGroup(pnlRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRoundLayout.setVerticalGroup(
            pnlRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblScore)
                .addGap(18, 18, 18)
                .addGroup(pnlRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGo)
                    .addComponent(btnStop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInst1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInst2)
                            .addComponent(lblInst3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRound, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalScore, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHighScore, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInst1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInst2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInst3)
                .addGap(18, 18, 18)
                .addComponent(lblHighScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRound)
                    .addComponent(lblTotalScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStart)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        
        // Variables
        int [] rolls;
        boolean isDoubles;
        
        // Reset total score
        totalScore = 0;
        
        // Roll the dice
        rolls = rollDice();

        // Check if doubles were rolled
        isDoubles = checkDoubles(rolls);
        
        if (isDoubles) {
            endRound();
            
            // Set the dice background to red
            lblDice1.setBackground(new java.awt.Color(255, 0, 0));
            lblDice2.setBackground(new java.awt.Color(255, 0, 0));
        } else {
            // Increase score
            score += rolls[0] + 1 + rolls[1] + 1;
            
            // Allow the user to stop
            btnStop.setEnabled(true);
            
            // Reset the dice background
            lblDice1.setBackground(new java.awt.Color(255, 255, 255));
            lblDice2.setBackground(new java.awt.Color(255, 255, 255));
        }

        displayDiceFaces(rolls);
        
        outputData();
        
        // Disable the start button and enable the go button
        btnStart.setEnabled(false);
        btnGo.setEnabled(true);
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        
        // Variables
        int [] rolls;
        boolean isDoubles;
        
        // Roll the dice
        rolls = rollDice();

        // Check if doubles were rolled
        isDoubles = checkDoubles(rolls);

        if (isDoubles) {
            endRound();
            
            // Set the dice background to red
            lblDice1.setBackground(new java.awt.Color(255, 0, 0));
            lblDice2.setBackground(new java.awt.Color(255, 0, 0));
        } else {
            // Increase score
            score += rolls[0] + 1 + rolls[1] + 1;
            
            // Allow the user to stop
            btnStop.setEnabled(true);
            
             // Reset the dice background
            lblDice1.setBackground(new java.awt.Color(255, 255, 255));
            lblDice2.setBackground(new java.awt.Color(255, 255, 255));
        }
        
        displayDiceFaces(rolls);
        
        outputData();
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        
        // Increase the total score by score
        totalScore += score;
        
        endRound();
        
        // Increase high score if needed
        if (totalScore > highScore) {
            highScore = totalScore;
        }

        outputData();
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDoublesJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDoublesJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDoublesJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDoublesJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDoublesJW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblDice1;
    private javax.swing.JLabel lblDice2;
    private javax.swing.JLabel lblHighScore;
    private javax.swing.JLabel lblInst1;
    private javax.swing.JLabel lblInst2;
    private javax.swing.JLabel lblInst3;
    private javax.swing.JLabel lblRound;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalScore;
    private javax.swing.JPanel pnlRound;
    // End of variables declaration//GEN-END:variables
}
