/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jijwa
 */
public class frmMakingPurchasesWatson extends javax.swing.JFrame {
    
    // Methods
    static double round(double unRoundedNumber) {
        double roundedNumber = (double)Math.round(unRoundedNumber * 100) / 100; // Rounds the number
        return roundedNumber;
    }
    /**
     * Creates new form frmMakingPurchasesWatson
     */
    public frmMakingPurchasesWatson() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JTabbedPane();
        pnlStore = new javax.swing.JPanel();
        btnPurchase = new javax.swing.JButton();
        imgYellowDog = new javax.swing.JLabel();
        imgRobotDog = new javax.swing.JLabel();
        lblYellowDog = new javax.swing.JLabel();
        lblRobotDog = new javax.swing.JLabel();
        lblSmallDogPrice = new javax.swing.JLabel();
        spnRobotDog = new javax.swing.JSpinner();
        lblYellowDogPrice = new javax.swing.JLabel();
        spnYellowDog = new javax.swing.JSpinner();
        imgBlackDog = new javax.swing.JLabel();
        imgSmallDog = new javax.swing.JLabel();
        lblBlackDog = new javax.swing.JLabel();
        lblSmallDog = new javax.swing.JLabel();
        lblBlackDogPrice = new javax.swing.JLabel();
        spnBlackDog = new javax.swing.JSpinner();
        lblRobotDogPrice = new javax.swing.JLabel();
        spnSmallDog = new javax.swing.JSpinner();
        pnlCheckOut = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        pnlReciept = new javax.swing.JPanel();
        lblBlackDogCost = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblSubTotalHeader = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblDiscountHeader = new javax.swing.JLabel();
        lblYellowDogHeader = new javax.swing.JLabel();
        lblYellowDogCost = new javax.swing.JLabel();
        lblTotalHeader = new javax.swing.JLabel();
        lblSmallDogCost = new javax.swing.JLabel();
        lblGrandTotalHeader = new javax.swing.JLabel();
        lblRobotDogHeader = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblRobotDogCost = new javax.swing.JLabel();
        lblTaxHeader = new javax.swing.JLabel();
        lblSmallDogHeader = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblBlackDogHeader = new javax.swing.JLabel();
        pnlCoupon = new javax.swing.JPanel();
        btnApplyCoupon = new javax.swing.JButton();
        lblCoupon = new javax.swing.JLabel();
        txtCoupon = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dog Warehouse");
        setBackground(new java.awt.Color(255, 255, 255));

        pnlMain.setEnabled(false);

        pnlStore.setOpaque(false);

        btnPurchase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPurchase.setText("Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        imgYellowDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yellow_dog.jpg"))); // NOI18N

        imgRobotDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robot_dog.jpg"))); // NOI18N

        lblYellowDog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblYellowDog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYellowDog.setText("Yellow Dog");

        lblRobotDog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRobotDog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRobotDog.setText("Robot Dog");

        lblSmallDogPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSmallDogPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSmallDogPrice.setText("$15.99");

        spnRobotDog.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblYellowDogPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblYellowDogPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYellowDogPrice.setText("$23.98");

        spnYellowDog.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        imgBlackDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_dog.jpg"))); // NOI18N
        imgBlackDog.setText("jLabel12");

        imgSmallDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_dog.jpg"))); // NOI18N
        imgSmallDog.setText("jLabel13");

        lblBlackDog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBlackDog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlackDog.setText("Black Dog");

        lblSmallDog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSmallDog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSmallDog.setText("Small Dog");

        lblBlackDogPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBlackDogPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlackDogPrice.setText("$35.88");

        spnBlackDog.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblRobotDogPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRobotDogPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRobotDogPrice.setText("$320.99");

        spnSmallDog.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout pnlStoreLayout = new javax.swing.GroupLayout(pnlStore);
        pnlStore.setLayout(pnlStoreLayout);
        pnlStoreLayout.setHorizontalGroup(
            pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStoreLayout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStoreLayout.createSequentialGroup()
                        .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRobotDog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStoreLayout.createSequentialGroup()
                                    .addComponent(lblRobotDogPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spnRobotDog, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(imgRobotDog, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(100, 100, 100)
                        .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imgYellowDog, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblYellowDog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlStoreLayout.createSequentialGroup()
                                .addComponent(lblYellowDogPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spnYellowDog, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlStoreLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlStoreLayout.createSequentialGroup()
                                .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlStoreLayout.createSequentialGroup()
                                        .addComponent(lblBlackDogPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spnBlackDog, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(imgBlackDog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBlackDog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(100, 100, 100)
                                .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imgSmallDog, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSmallDog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlStoreLayout.createSequentialGroup()
                                        .addComponent(lblSmallDogPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spnSmallDog, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlStoreLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(99, 99, 99))
        );
        pnlStoreLayout.setVerticalGroup(
            pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYellowDog)
                    .addComponent(lblRobotDog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imgYellowDog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgRobotDog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnRobotDog)
                    .addComponent(lblYellowDogPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnYellowDog)
                    .addComponent(lblRobotDogPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlackDog)
                    .addComponent(lblSmallDog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgSmallDog)
                    .addComponent(imgBlackDog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(pnlStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlackDogPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnBlackDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSmallDogPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnSmallDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pnlMain.addTab("Store", pnlStore);

        pnlCheckOut.setOpaque(false);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        pnlReciept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlReciept.setOpaque(false);

        lblBlackDogCost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBlackDogCost.setText("0");

        lblTax.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTax.setText("0");

        lblSubTotalHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubTotalHeader.setText("Sub-Total:");

        lblDiscount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiscount.setText("0.0%");

        lblDiscountHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiscountHeader.setText("Discount:");

        lblYellowDogHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblYellowDogHeader.setText("Yellow Dog: ");

        lblYellowDogCost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblYellowDogCost.setText("0");

        lblTotalHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalHeader.setText("Total:");

        lblSmallDogCost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSmallDogCost.setText("0");

        lblGrandTotalHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGrandTotalHeader.setText("Grand Total");

        lblRobotDogHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRobotDogHeader.setText("Robot Dog:");

        lblSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubTotal.setText("0");

        lblRobotDogCost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRobotDogCost.setText("0");

        lblTaxHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTaxHeader.setText("Tax:");

        lblSmallDogHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSmallDogHeader.setText("Small Dog");

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGrandTotal.setText("0");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setText("0");

        lblBlackDogHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBlackDogHeader.setText("Black Dog: ");

        javax.swing.GroupLayout pnlRecieptLayout = new javax.swing.GroupLayout(pnlReciept);
        pnlReciept.setLayout(pnlRecieptLayout);
        pnlRecieptLayout.setHorizontalGroup(
            pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecieptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBlackDogHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYellowDogHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRobotDogHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubTotalHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSmallDogHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscountHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrandTotalHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTaxHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblSmallDogCost, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblTax, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblYellowDogCost, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblRobotDogCost, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblBlackDogCost, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRecieptLayout.setVerticalGroup(
            pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecieptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRobotDogHeader)
                    .addComponent(lblRobotDogCost))
                .addGap(18, 18, 18)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYellowDogHeader)
                    .addComponent(lblYellowDogCost))
                .addGap(18, 18, 18)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlackDogHeader)
                    .addComponent(lblBlackDogCost))
                .addGap(18, 18, 18)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSmallDogHeader)
                    .addComponent(lblSmallDogCost))
                .addGap(30, 30, 30)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalHeader)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscountHeader)
                    .addComponent(lblDiscount))
                .addGap(18, 18, 18)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotalHeader)
                    .addComponent(lblSubTotal))
                .addGap(18, 18, 18)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxHeader)
                    .addComponent(lblTax))
                .addGap(30, 30, 30)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrandTotalHeader)
                    .addComponent(lblGrandTotal))
                .addContainerGap())
        );

        pnlCoupon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlCoupon.setOpaque(false);

        btnApplyCoupon.setText("Apply");
        btnApplyCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyCouponActionPerformed(evt);
            }
        });

        lblCoupon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCoupon.setText("Coupon:");

        txtCoupon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCouponActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCouponLayout = new javax.swing.GroupLayout(pnlCoupon);
        pnlCoupon.setLayout(pnlCouponLayout);
        pnlCouponLayout.setHorizontalGroup(
            pnlCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCouponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnApplyCoupon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCouponLayout.createSequentialGroup()
                        .addComponent(lblCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCouponLayout.setVerticalGroup(
            pnlCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCouponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApplyCoupon)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCheckOutLayout = new javax.swing.GroupLayout(pnlCheckOut);
        pnlCheckOut.setLayout(pnlCheckOutLayout);
        pnlCheckOutLayout.setHorizontalGroup(
            pnlCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckOutLayout.createSequentialGroup()
                .addGroup(pnlCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCheckOutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCheckOutLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(pnlReciept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCheckOutLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(pnlCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        pnlCheckOutLayout.setVerticalGroup(
            pnlCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(pnlCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlReciept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        pnlMain.addTab("Check Out", pnlCheckOut);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Dog Warehouse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        // Returns the focus to the store page
        pnlMain.setSelectedIndex(0);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApplyCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyCouponActionPerformed
        // TODO add your handling code here:
        
        // Variables
        double total;
        double discount;
        double subTotal;
        double tax;
        double grandTotal;
        
        String couponCode;
        
        // Constants
        final String CORRECT_CODE = "WATSON";
        final double TAX_RATE = 0.13;
        
        // Get the coupon guess
        couponCode = txtCoupon.getText();
        
        // Get the total from the form
        total = Double.parseDouble(lblTotal.getText().replace("$", ""));
        
        // Add a 10% discount if the code is correct
        if (couponCode.equals(CORRECT_CODE)) {
            discount = -0.1;
        } else {
            txtCoupon.setText("INCORRECT");
            discount = 0;
        }
        
        // Calculations
        subTotal = round(total + total * discount);
        tax = round(subTotal * TAX_RATE);
        grandTotal = round(subTotal + tax);
        
        // Output the results
        lblDiscount.setText(String.valueOf(discount * 100)+"%");
        lblSubTotal.setText("$"+String.valueOf(subTotal));
        lblTax.setText("$"+String.valueOf(tax));
        lblGrandTotal.setText("$"+String.valueOf(grandTotal));
        
        
        
        
        
    }//GEN-LAST:event_btnApplyCouponActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        // TODO add your handling code here:
        
        // Variables
        int numRobotDog;
        int numYellowDog;
        int numBlackDog;
        int numSmallDog;
        
        double total;
        double discount;
        double subTotal;
        double tax;
        double grandTotal;
        
        double robotDogCost;
        double yellowDogCost;
        double blackDogCost;
        double smallDogCost;
        
        // Constants
        final double ROBOT_DOG_PRICE = 320.99;
        final double YELLOW_DOG_PRICE = 23.98;
        final double BLACK_DOG_PRICE = 35.88;
        final double SMALL_DOG_PRICE = 15.99;
        
        final double TAX_RATE = 0.13;
        
        // Collect input from spinners
        numRobotDog = (Integer)spnRobotDog.getValue();
        numYellowDog = (Integer)spnYellowDog.getValue();
        numBlackDog = (Integer)spnBlackDog.getValue();
        numSmallDog = (Integer)spnSmallDog.getValue();
        
        // Calculate costs
        robotDogCost = round(numRobotDog * ROBOT_DOG_PRICE);
        yellowDogCost = round(numYellowDog * YELLOW_DOG_PRICE);
        blackDogCost = round(numBlackDog * BLACK_DOG_PRICE);
        smallDogCost = round(numSmallDog * SMALL_DOG_PRICE);
        
        // Calcualte total, discount, subtotal and grand total
        total = round(robotDogCost + yellowDogCost + blackDogCost + smallDogCost);
        discount = Double.parseDouble(lblDiscount.getText().replace("%", "")) / 100;
        subTotal = round(total + total * discount);
        tax = round(subTotal * TAX_RATE);
        grandTotal = round(subTotal + tax);
        
        // output results
        lblRobotDogCost.setText("$"+String.valueOf(robotDogCost));
        lblYellowDogCost.setText("$"+String.valueOf(yellowDogCost));
        lblBlackDogCost.setText("$"+String.valueOf(blackDogCost));
        lblSmallDogCost.setText("$"+String.valueOf(smallDogCost));
        
        lblTotal.setText("$"+String.valueOf(total));
        lblSubTotal.setText("$"+String.valueOf(subTotal));
        lblTax.setText("$"+String.valueOf(tax));
        lblGrandTotal.setText("$"+String.valueOf(grandTotal));
        
        // Set the focus to the Checkout panel
        pnlMain.setSelectedIndex(1);
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void txtCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCouponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCouponActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMakingPurchasesWatson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMakingPurchasesWatson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMakingPurchasesWatson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMakingPurchasesWatson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMakingPurchasesWatson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyCoupon;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JLabel imgBlackDog;
    private javax.swing.JLabel imgRobotDog;
    private javax.swing.JLabel imgSmallDog;
    private javax.swing.JLabel imgYellowDog;
    private javax.swing.JLabel lblBlackDog;
    private javax.swing.JLabel lblBlackDogCost;
    private javax.swing.JLabel lblBlackDogHeader;
    private javax.swing.JLabel lblBlackDogPrice;
    private javax.swing.JLabel lblCoupon;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDiscountHeader;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblGrandTotalHeader;
    private javax.swing.JLabel lblRobotDog;
    private javax.swing.JLabel lblRobotDogCost;
    private javax.swing.JLabel lblRobotDogHeader;
    private javax.swing.JLabel lblRobotDogPrice;
    private javax.swing.JLabel lblSmallDog;
    private javax.swing.JLabel lblSmallDogCost;
    private javax.swing.JLabel lblSmallDogHeader;
    private javax.swing.JLabel lblSmallDogPrice;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblSubTotalHeader;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTaxHeader;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalHeader;
    private javax.swing.JLabel lblYellowDog;
    private javax.swing.JLabel lblYellowDogCost;
    private javax.swing.JLabel lblYellowDogHeader;
    private javax.swing.JLabel lblYellowDogPrice;
    private javax.swing.JPanel pnlCheckOut;
    private javax.swing.JPanel pnlCoupon;
    private javax.swing.JTabbedPane pnlMain;
    private javax.swing.JPanel pnlReciept;
    private javax.swing.JPanel pnlStore;
    private javax.swing.JSpinner spnBlackDog;
    private javax.swing.JSpinner spnRobotDog;
    private javax.swing.JSpinner spnSmallDog;
    private javax.swing.JSpinner spnYellowDog;
    private javax.swing.JTextField txtCoupon;
    // End of variables declaration//GEN-END:variables
}
