/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jijwa
 */
public class frmPutridPizzaJW extends javax.swing.JFrame {
    // Methods
    static double round(double unRoundedNumber) {
        double roundedNumber = (double)Math.round(unRoundedNumber * 100) / 100; // Rounds the number
        return roundedNumber;
    }
    
    /**
     * Creates new form frmPutridPizzaJW
     */
    public frmPutridPizzaJW() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(89, 89, 71));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sldDiameter = new javax.swing.JSlider();
        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblAnchovies = new javax.swing.JLabel();
        lblOlives = new javax.swing.JLabel();
        lblDiameter = new javax.swing.JLabel();
        lblDiameterHeading = new javax.swing.JLabel();
        btnPurchase = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblGrandTotalHeading = new javax.swing.JLabel();
        lblSubTotalHeading = new javax.swing.JLabel();
        lblTaxHeading = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Putrid Pizza");

        sldDiameter.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        sldDiameter.setMaximum(60);
        sldDiameter.setMinimum(1);
        sldDiameter.setToolTipText("");
        sldDiameter.setValue(30);
        sldDiameter.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        sldDiameter.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sldDiameterMouseDragged(evt);
            }
        });

        pnlHeader.setBackground(new java.awt.Color(102, 102, 0));

        lblTitle.setBackground(new java.awt.Color(102, 102, 0));
        lblTitle.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Putrid Pizza");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle)
        );

        lblAnchovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anchovies.jpg"))); // NOI18N
        lblAnchovies.setText("jLabel2");

        lblOlives.setIcon(new javax.swing.ImageIcon(getClass().getResource("/olives.jpg"))); // NOI18N
        lblOlives.setText("jLabel3");

        lblDiameter.setBackground(new java.awt.Color(204, 204, 0));
        lblDiameter.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        lblDiameter.setForeground(new java.awt.Color(204, 0, 51));
        lblDiameter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiameter.setText("30 cm");
        lblDiameter.setOpaque(true);

        lblDiameterHeading.setBackground(new java.awt.Color(204, 204, 0));
        lblDiameterHeading.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        lblDiameterHeading.setForeground(new java.awt.Color(204, 0, 51));
        lblDiameterHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiameterHeading.setText("Diameter of Pizza");
        lblDiameterHeading.setOpaque(true);

        btnPurchase.setBackground(new java.awt.Color(204, 0, 0));
        btnPurchase.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        btnPurchase.setForeground(new java.awt.Color(204, 204, 0));
        btnPurchase.setText("Purchase Pizza");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(204, 204, 204));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Our pizzas are delicious!");

        lblGrandTotalHeading.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblGrandTotalHeading.setForeground(new java.awt.Color(204, 204, 204));
        lblGrandTotalHeading.setText("GRAND TOTAL");

        lblSubTotalHeading.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblSubTotalHeading.setForeground(new java.awt.Color(204, 204, 204));
        lblSubTotalHeading.setText("SUBTOTAL:");

        lblTaxHeading.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblTaxHeading.setForeground(new java.awt.Color(204, 204, 204));
        lblTaxHeading.setText("TAX:");

        lblSubTotal.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(204, 204, 204));
        lblSubTotal.setText("$0.00");

        lblTax.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblTax.setForeground(new java.awt.Color(204, 204, 204));
        lblTax.setText("$0.00");

        lblGrandTotal.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(204, 204, 204));
        lblGrandTotal.setText("$0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAnchovies, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sldDiameter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDiameter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDiameterHeading))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblOlives, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGrandTotalHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTaxHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSubTotalHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAnchovies)
                    .addComponent(lblOlives)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiameterHeading)
                        .addGap(0, 0, 0)
                        .addComponent(lblDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnPurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotalHeading)
                    .addComponent(lblSubTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxHeading)
                    .addComponent(lblTax))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrandTotalHeading)
                    .addComponent(lblGrandTotal))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldDiameterMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldDiameterMouseDragged
        // TODO add your handling code here:
        
        // Variables
        double diameter;
        
        // Get the diameter from the slider
        diameter = sldDiameter.getValue();
        
        // Output the diameter
        lblDiameter.setText(String.valueOf(diameter) + " cm");
    }//GEN-LAST:event_sldDiameterMouseDragged

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        // TODO add your handling code here:
        
        // Variables
        double diameter;
        double subTotal;
        double tax;
        double grandTotal;
        
        String message;
        
        // Constants
        final double LABOUR_CHARGE = 0.75;
        final double RENT_CHARGE = 0.99;
        final double INGREDIENTS_CHARGE = 0.50;
        
        final double TAX_RATE = 0.13;
        
        final String BIG_MESSAGE = "Whoa, big pizza! You might need a truck to get this home!";
        final String MEDIUM_MESSAGE = "This will be delicious!";
        final String SMALL_MESSAGE = "We are going to make you a cute little pizza!";
        final String DEFAULT_MESSAGE = "Our pizzas are delicious";
        
        // Get diameter from slider
        diameter = sldDiameter.getValue();
        
        // Calculate the welcome Message;
        if (diameter > 40)
        {
            message = BIG_MESSAGE;
        }
        else if ((diameter < 40) && (diameter > 20))
        {
            message = MEDIUM_MESSAGE;
        }
        else if ((diameter >= 1) && (diameter <= 15))
        {
            message = SMALL_MESSAGE;
        }
        else
        {
            message = DEFAULT_MESSAGE;
        }
        
        // Calculate sub-total, tax and grand total
        subTotal = round(diameter * INGREDIENTS_CHARGE + RENT_CHARGE + LABOUR_CHARGE);
        tax = round(subTotal * TAX_RATE);
        grandTotal = round(subTotal + tax);
        
        //Output results
        lblMessage.setText(message);
        
        lblSubTotal.setText("$" + String.valueOf(subTotal));
        lblTax.setText("$" + String.valueOf(tax));
        lblGrandTotal.setText("$" + String.valueOf(grandTotal));
    }//GEN-LAST:event_btnPurchaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPutridPizzaJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPutridPizzaJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPutridPizzaJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPutridPizzaJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPutridPizzaJW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPurchase;
    private javax.swing.JLabel lblAnchovies;
    private javax.swing.JLabel lblDiameter;
    private javax.swing.JLabel lblDiameterHeading;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblGrandTotalHeading;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblOlives;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblSubTotalHeading;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTaxHeading;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JSlider sldDiameter;
    // End of variables declaration//GEN-END:variables
}
