
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jijwa
 */
public class frmTestForm extends javax.swing.JFrame {
    // Global Variables
    String imagePath = "";
    int buttonIndex = 0;
    
    // Methods
    public static javax.swing.JLabel [] append (javax.swing.JLabel [] array, javax.swing.JLabel newElement) {
        javax.swing.JLabel [] temp = new javax.swing.JLabel [array.length + 1];
        for (int i = 0; i < array.length; i ++) {
            temp[i] = array[i];
        }
        temp[array.length] = new javax.swing.JLabel();
        array = temp;

        return array;
    }
    public static javax.swing.JPanel [] append (javax.swing.JPanel [] array, javax.swing.JPanel newElement) {
        javax.swing.JPanel [] temp = new javax.swing.JPanel [array.length + 1];
        for (int i = 0; i < array.length; i ++) {
            temp[i] = array[i];
        }
        temp[array.length] = new javax.swing.JPanel();
        array = temp;

        return array;
    }
    public static javax.swing.JLayeredPane [] append (javax.swing.JLayeredPane [] array, javax.swing.JLayeredPane newElement) {
        javax.swing.JLayeredPane [] temp = new javax.swing.JLayeredPane [array.length + 1];
        for (int i = 0; i < array.length; i ++) {
            temp[i] = array[i];
        }
        temp[array.length] = new javax.swing.JLayeredPane();
        array = temp;

        return array;
    }
    public static javax.swing.JButton [] append (javax.swing.JButton [] array, javax.swing.JButton newElement) {
        javax.swing.JButton [] temp = new javax.swing.JButton [array.length + 1];
        for (int i = 0; i < array.length; i ++) {
            temp[i] = array[i];
        }
        temp[array.length] = new javax.swing.JButton();
        array = temp;

        return array;
    }
    
    public static javax.swing.JLabel [] remove (javax.swing.JLabel [] array, int index) {
        javax.swing.JLabel [] temp = new javax.swing.JLabel [array.length - 1];
        for (int i = 0; i < array.length; i ++) {
            if (i < index) {
                temp[i] = array[i];
            } else if (i > index) {
                temp[i - 1] = array[i];
            }
        }
        
        array = temp;
        return array;
    }
    public static javax.swing.JPanel [] remove (javax.swing.JPanel [] array, int index) {
        javax.swing.JPanel [] temp = new javax.swing.JPanel [array.length - 1];
        for (int i = 0; i < array.length; i ++) {
            if (i < index) {
                temp[i] = array[i];
            } else if (i > index) {
                temp[i - 1] = array[i];
            }
        }
        
        array = temp;
        return array;
    }
    public static javax.swing.JLayeredPane [] remove (javax.swing.JLayeredPane [] array, int index) {
        javax.swing.JLayeredPane [] temp = new javax.swing.JLayeredPane [array.length - 1];
        for (int i = 0; i < array.length; i ++) {
            if (i < index) {
                temp[i] = array[i];
            } else if (i > index) {
                temp[i - 1] = array[i];
            }
        }
        
        array = temp;
        return array;
    }
    public static javax.swing.JButton [] remove (javax.swing.JButton [] array, int index) {
        javax.swing.JButton [] temp = new javax.swing.JButton [array.length - 1];
        for (int i = 0; i < array.length; i ++) {
            if (i < index) {
                temp[i] = array[i];
            } else if (i > index) {
                temp[i - 1] = array[i];
            }
        }
        
        array = temp;
        return array;
    }

    /**
     * Creates new form frmTestForm
     */
    public frmTestForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fchUpload = new javax.swing.JFileChooser();
        pmnEdit = new javax.swing.JPopupMenu();
        mnuEdit = new javax.swing.JMenuItem();
        mnuDelete = new javax.swing.JMenuItem();
        dlgCheckDelete = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();

        fchUpload.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        fchUpload.setApproveButtonText("Upload");
        fchUpload.setApproveButtonToolTipText("Upload an Image");
        fchUpload.setBackground(new java.awt.Color(255, 255, 255));
        fchUpload.setDialogTitle("Upload an Image");
        fchUpload.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fchUpload.setMinimumSize(new java.awt.Dimension(588, 328));
        fchUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fchUploadActionPerformed(evt);
            }
        });

        mnuEdit.setText("Edit");
        mnuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditActionPerformed(evt);
            }
        });
        pmnEdit.add(mnuEdit);

        mnuDelete.setText("Delete");
        mnuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteActionPerformed(evt);
            }
        });
        pmnEdit.add(mnuDelete);

        dlgCheckDelete.setAlwaysOnTop(true);
        dlgCheckDelete.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Are you sure you want to delete this recipe?");

        jToggleButton2.setText("Cancel");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("This action CAN NOT be undonde!");

        jToggleButton1.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButton1.setText("Delete");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgCheckDeleteLayout = new javax.swing.GroupLayout(dlgCheckDelete.getContentPane());
        dlgCheckDelete.getContentPane().setLayout(dlgCheckDeleteLayout);
        dlgCheckDeleteLayout.setHorizontalGroup(
            dlgCheckDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgCheckDeleteLayout.setVerticalGroup(
            dlgCheckDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jButton1.setText("Generate New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete Old");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Name:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        lblImage.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Image:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        lblImage.setOpaque(true);
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        getContentPane().setLayout(layout);

        // Create new element
        lpnRecipes = append(lpnRecipes, new javax.swing.JLayeredPane());
        pnlEditRecipes = append(pnlEditRecipes, new javax.swing.JPanel());
        btnEditRecipes = append(btnEditRecipes, new javax.swing.JButton());
        pnlRecipes = append(pnlRecipes, new javax.swing.JPanel());
        lblRecipeImages = append(lblRecipeImages, new javax.swing.JLabel());
        lblRecipeTitles = append(lblRecipeTitles, new javax.swing.JLabel());

        // Variables
        int lastIndex = lpnRecipes.length - 1;
        String recipeName = txtName.getText();

        // Format components
        lpnRecipes[lastIndex].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        pnlEditRecipes[lastIndex].setOpaque(false);

        btnEditRecipes[lastIndex].setFont(new java.awt.Font("Arial Black", 0, 12));
        btnEditRecipes[lastIndex].setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png")));
        btnEditRecipes[lastIndex].setBorder(null);
        btnEditRecipes[lastIndex].setHideActionText(true);
        btnEditRecipes[lastIndex].addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRecipesActionPerformed(evt, lastIndex);
            }
        });

        pnlRecipes[lastIndex].setBackground(new java.awt.Color(255, 255, 255));
        if (!"".equals(imagePath)) {
            lblRecipeImages[lastIndex].setIcon(new javax.swing.ImageIcon(getClass().getResource(imagePath)));
        }
        lblRecipeTitles[lastIndex].setFont(new java.awt.Font("Gill Sans MT", 0, 18));
        lblRecipeTitles[lastIndex].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecipeTitles[lastIndex].setText(recipeName);
        lblRecipeTitles[lastIndex].setVerticalAlignment(javax.swing.SwingConstants.TOP);


        // Align components
        javax.swing.GroupLayout pnlEditRecipeLayout = new javax.swing.GroupLayout(pnlEditRecipes[lastIndex]);
        pnlEditRecipes[lastIndex].setLayout(pnlEditRecipeLayout);
        pnlEditRecipeLayout.setHorizontalGroup(
            pnlEditRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditRecipeLayout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addComponent(btnEditRecipes[lastIndex]))
        );
        pnlEditRecipeLayout.setVerticalGroup(
            pnlEditRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditRecipeLayout.createSequentialGroup()
                .addComponent(btnEditRecipes[lastIndex])
                .addGap(0, 90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRecipeLayout = new javax.swing.GroupLayout(pnlRecipes[lastIndex]);
        pnlRecipes[lastIndex].setLayout(pnlRecipeLayout);
        pnlRecipeLayout.setHorizontalGroup(
            pnlRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecipeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRecipeTitles[lastIndex], javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlRecipeLayout.createSequentialGroup()
                .addComponent(lblRecipeImages[lastIndex])
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRecipeLayout.setVerticalGroup(
            pnlRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecipeLayout.createSequentialGroup()
                .addComponent(lblRecipeImages[lastIndex], javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRecipeTitles[lastIndex], javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        lpnRecipes[lastIndex].setLayer(pnlEditRecipes[lastIndex], javax.swing.JLayeredPane.POPUP_LAYER);
        lpnRecipes[lastIndex].setLayer(pnlRecipes[lastIndex], javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpnRecipeLayout = new javax.swing.GroupLayout(lpnRecipes[lastIndex]);
        lpnRecipes[lastIndex].setLayout(lpnRecipeLayout);
        lpnRecipeLayout.setHorizontalGroup(
            lpnRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRecipes[lastIndex], javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lpnRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpnRecipeLayout.createSequentialGroup()
                    .addContainerGap(141, Short.MAX_VALUE)
                    .addComponent(pnlEditRecipes[lastIndex], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        lpnRecipeLayout.setVerticalGroup(
            lpnRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRecipes[lastIndex], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(lpnRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lpnRecipeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlEditRecipes[lastIndex], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE)))
        );

        // Place the card in it's proper place
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap((lastIndex * 320) % 1280 + 25, (lastIndex * 320) % 1280 + 25, (lastIndex * 320) % 1280 + 25)
                .addComponent(lpnRecipes[lastIndex], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap((3 - lastIndex % 4) * 320 + 25, Short.MAX_VALUE))
        );
        System.out.println((lastIndex * 320) % 1280 + 25);
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap((lastIndex / 4) * 334 + 25, (lastIndex / 4) * 334 + 25, (lastIndex / 4) * 334 + 25)
                .addComponent(lpnRecipes[lastIndex], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );


        revalidate();

        imagePath = "";
        lblImage.setIcon(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditRecipesActionPerformed(java.awt.event.ActionEvent evt, int index) {
        // TODO add your handling code here:
        int x = java.awt.MouseInfo.getPointerInfo().getLocation().x - jPanel1.getLocationOnScreen().x;
        int y = java.awt.MouseInfo.getPointerInfo().getLocation().y - jPanel1.getLocationOnScreen().y;
        
        pmnEdit.show(jPanel1, x, y);
        buttonIndex = index;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        for (int i = 0; i < 4; i ++) {
            
            long time = System.currentTimeMillis();
            while (System.currentTimeMillis() - time < 800) {}
            
            
            layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            
            killMes = append(killMes, new javax.swing.JLabel());
            killMes[i].setText("KIll ME");
            killMes[i].setOpaque(true);
            killMes[i].setBackground(new java.awt.Color(255, 20, 20));
            
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50 * i)
                    .addComponent(killMes[i], 100, 100, 100)
                    .addContainerGap(230, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20)
                    .addComponent(killMes[i], 100, 100, 100)
                    .addContainerGap(251, Short.MAX_VALUE))
            );
            
            revalidate();
            
        }
        
        
        
//        int lastIndex = killMes.length - 1;
//
//        if (lastIndex >= 0) {
//            getContentPane().setLayout(layout);
//
//            getContentPane().remove(killMes[lastIndex]);
//
//            javax.swing.JLabel [] temp = new javax.swing.JLabel [killMes.length - 1];
//            for (int i = 0; i < killMes.length - 1; i ++) {
//                temp[i] = killMes[i];
//            }
//            killMes = temp;
//
//            layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(layout.createSequentialGroup()
//                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING))
//                    .addContainerGap(230, Short.MAX_VALUE))
//            );
//            layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(layout.createSequentialGroup()
//                    .addContainerGap(251, Short.MAX_VALUE))
//            );
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void fchUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fchUploadActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fchUploadActionPerformed

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        // TODO add your handling code here:
        
        
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading.png")));
        int returnVal = fchUpload.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
                    if (!imagePath.equals("")) {
                        File oldImage = new File("src/" + imagePath);
                        oldImage.delete();
                        lblImage.setIcon(null);
                    }
            
            
            File imageFile = fchUpload.getSelectedFile();
            try {
                java.awt.image.BufferedImage uploadedImage = ImageIO.read(imageFile);

                java.awt.image.BufferedImage resizedImage = new java.awt.image.BufferedImage(270, 150, java.awt.image.BufferedImage.TYPE_INT_RGB);
                java.awt.Graphics2D graphics2D = resizedImage.createGraphics();
                graphics2D.drawImage(uploadedImage, 0, 0, 270, 150, null);
                graphics2D.dispose();
                String imageName = String.valueOf(System.currentTimeMillis());
                ImageIO.write(resizedImage, "jpg", new File("src/" + imageName + ".jpg"));
                imagePath = "/" + imageName + ".jpg";
                System.out.println(imagePath);
                while (getClass().getResource(imagePath) == null) {}
                
                lblImage.setIcon(new javax.swing.ImageIcon(resizedImage));

            } catch (IOException e) {
                System.out.println("problem accessing file" + imageFile.getAbsolutePath());
            }
        } else {
            if (!imagePath.equals("")) {
                lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagePath)));
            } else {
                lblImage.setIcon(null);
            }
            System.out.println("File access cancelled by user.");
        }     
    }//GEN-LAST:event_lblImageMouseClicked

    private void mnuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteActionPerformed
        // TODO add your handling code here:
        dlgCheckDelete.setVisible(true);
        dlgCheckDelete.pack();
        
    }//GEN-LAST:event_mnuDeleteActionPerformed

    private void mnuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuEditActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        int index = buttonIndex;
        
        jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        
        for (int i = 0; i < lpnRecipes.length; i ++) {
            jPanel1.remove(lpnRecipes[i]);
        }
        
        
        // Update the arrays
        lpnRecipes = remove(lpnRecipes, index);
        pnlEditRecipes = remove(pnlEditRecipes, index);
        btnEditRecipes = remove(btnEditRecipes, index);
        pnlRecipes = remove(pnlRecipes, index);
        lblRecipeImages = remove(lblRecipeImages, index);
        lblRecipeTitles = remove(lblRecipeTitles, index);
        
        // Update the event listeners
        for (int i = 0; i < lpnRecipes.length; i ++) {
            int j = i;
            btnEditRecipes[i].removeActionListener(btnEditRecipes[i].getActionListeners()[0]);
            btnEditRecipes[i].addActionListener((java.awt.event.ActionEvent evt1) -> {
                btnEditRecipesActionPerformed(evt1, j);
            });
        }
        
        // Update the parent panel
        for (int i = 0; i < lpnRecipes.length; i ++) {
            System.out.println("INDEX IS: " + i);
            System.out.println("POS IS: " + ((i * 320) % 1280 + 25));
            jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap((i * 320) % 1280 + 25, (i * 320) % 1280 + 25, (i * 320) % 1280 + 25)
                    .addComponent(lpnRecipes[i], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap((3 - i % 4) * 320 + 25, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap((i / 4) * 334 + 25, (i / 4) * 334 + 25, (i / 4) * 334 + 25)
                    .addComponent(lpnRecipes[i], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE))
            );
            dlgCheckDelete.setVisible(false);
            revalidate();
            
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        dlgCheckDelete.setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgCheckDelete;
    private javax.swing.JFileChooser fchUpload;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JMenuItem mnuDelete;
    private javax.swing.JMenuItem mnuEdit;
    private javax.swing.JPopupMenu pmnEdit;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    // Private Variables
    private javax.swing.JLabel [] killMes = {};
    private javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    private javax.swing.GroupLayout jPanel1Layout;
    
    private javax.swing.JLayeredPane [] lpnRecipes = {};
    private javax.swing.JPanel [] pnlEditRecipes = {};
    private javax.swing.JButton [] btnEditRecipes = {};
    private javax.swing.JPanel [] pnlRecipes = {};
    private javax.swing.JLabel [] lblRecipeImages = {};
    private javax.swing.JLabel [] lblRecipeTitles = {};
}
