
// Imports to allow opening links
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.net.URL;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jijwa
 */
public class frmNetflixShowSelectorJW extends javax.swing.JFrame {

    // Methods
    
    // Check if a value is in an array
    static boolean isIn(String value, String [ ] array) {
        for (String element : array) {
            if (value.equals(element)) {
                return true;
            }
        }
        return false;
    }
    
    // Append an array to another array
    static String [][] append(String [][] newArray, String [][] originalArray) {
        // Variables
        int originalArraySize = originalArray.length;
        int newArraySize = newArray.length;
        
        String [][] tempArray = new String [newArraySize + originalArraySize][4];

        System.arraycopy(originalArray, 0, tempArray, 0, originalArraySize);
        System.arraycopy(newArray, 0, tempArray, originalArraySize, newArraySize);
        originalArray = new String [newArraySize + originalArraySize][4];
        System.arraycopy(tempArray, 0, originalArray, 0, newArraySize + originalArraySize);
        
        return originalArray;
    }
    
    // Global Variables
    String [] movieLink = new String [4];
            
    /**
     * Creates new form frmNetflixShowSelectorJW
     */
    public frmNetflixShowSelectorJW() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(80, 80, 80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMovie = new javax.swing.JPanel();
        lblMovie1 = new javax.swing.JLabel();
        lblMovie2 = new javax.swing.JLabel();
        lblMovie3 = new javax.swing.JLabel();
        lblMovie4 = new javax.swing.JLabel();
        lblPoster1 = new javax.swing.JLabel();
        lblPoster3 = new javax.swing.JLabel();
        lblPoster4 = new javax.swing.JLabel();
        lblPoster2 = new javax.swing.JLabel();
        btnWatch2 = new javax.swing.JButton();
        btnWatch3 = new javax.swing.JButton();
        btnWatch1 = new javax.swing.JButton();
        btnWatch4 = new javax.swing.JButton();
        lblRating1 = new javax.swing.JLabel();
        lblRating4 = new javax.swing.JLabel();
        lblRating3 = new javax.swing.JLabel();
        lblRating2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblInst1 = new javax.swing.JLabel();
        lblInst2 = new javax.swing.JLabel();
        lblControl = new javax.swing.JPanel();
        lblRating = new javax.swing.JLabel();
        cbxG = new javax.swing.JCheckBox();
        cbxPG = new javax.swing.JCheckBox();
        cbxPG13 = new javax.swing.JCheckBox();
        btnGenerateMovies = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Netflix Movie Selector");

        pnlMovie.setBackground(new java.awt.Color(51, 51, 51));
        pnlMovie.setPreferredSize(new java.awt.Dimension(150, 210));

        lblMovie1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMovie1.setForeground(new java.awt.Color(255, 255, 255));
        lblMovie1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovie1.setText("??");

        lblMovie2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMovie2.setForeground(new java.awt.Color(255, 255, 255));
        lblMovie2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovie2.setText("??");

        lblMovie3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMovie3.setForeground(new java.awt.Color(255, 255, 255));
        lblMovie3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovie3.setText("??");

        lblMovie4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMovie4.setForeground(new java.awt.Color(255, 255, 255));
        lblMovie4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovie4.setText("??");

        lblPoster1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placeholder.jpg"))); // NOI18N
        lblPoster1.setMaximumSize(new java.awt.Dimension(150, 223));

        lblPoster3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placeholder.jpg"))); // NOI18N
        lblPoster3.setMaximumSize(new java.awt.Dimension(150, 223));

        lblPoster4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placeholder.jpg"))); // NOI18N
        lblPoster4.setMaximumSize(new java.awt.Dimension(150, 223));

        lblPoster2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placeholder.jpg"))); // NOI18N
        lblPoster2.setMaximumSize(new java.awt.Dimension(150, 223));

        btnWatch2.setBackground(new java.awt.Color(232, 0, 0));
        btnWatch2.setForeground(new java.awt.Color(255, 255, 255));
        btnWatch2.setText("Watch");
        btnWatch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWatch2ActionPerformed(evt);
            }
        });

        btnWatch3.setBackground(new java.awt.Color(232, 0, 0));
        btnWatch3.setForeground(new java.awt.Color(255, 255, 255));
        btnWatch3.setText("Watch");
        btnWatch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWatch3ActionPerformed(evt);
            }
        });

        btnWatch1.setBackground(new java.awt.Color(232, 0, 0));
        btnWatch1.setForeground(new java.awt.Color(255, 255, 255));
        btnWatch1.setText("Watch");
        btnWatch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWatch1ActionPerformed(evt);
            }
        });

        btnWatch4.setBackground(new java.awt.Color(232, 0, 0));
        btnWatch4.setForeground(new java.awt.Color(255, 255, 255));
        btnWatch4.setText("Watch");
        btnWatch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWatch4ActionPerformed(evt);
            }
        });

        lblRating1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRating1.setForeground(new java.awt.Color(232, 0, 0));
        lblRating1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRating4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRating4.setForeground(new java.awt.Color(232, 0, 0));
        lblRating4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRating3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRating3.setForeground(new java.awt.Color(232, 0, 0));
        lblRating3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRating2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRating2.setForeground(new java.awt.Color(232, 0, 0));
        lblRating2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlMovieLayout = new javax.swing.GroupLayout(pnlMovie);
        pnlMovie.setLayout(pnlMovieLayout);
        pnlMovieLayout.setHorizontalGroup(
            pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovieLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRating1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMovie1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMovie2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblRating2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblRating3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMovie3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMovie4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblRating4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMovieLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWatch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPoster1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnWatch2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoster2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPoster3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWatch3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPoster4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWatch4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
        );
        pnlMovieLayout.setVerticalGroup(
            pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMovie3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMovie4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMovie1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMovie2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblRating1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRating3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRating2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(lblRating4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMovieLayout.createSequentialGroup()
                        .addComponent(lblPoster1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWatch1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMovieLayout.createSequentialGroup()
                        .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPoster2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPoster3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPoster4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnWatch2)
                            .addComponent(btnWatch3)
                            .addComponent(btnWatch4))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lblTitle.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(232, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Netflix Movie Selector");
        lblTitle.setOpaque(true);

        lblInst1.setBackground(new java.awt.Color(51, 51, 51));
        lblInst1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInst1.setForeground(new java.awt.Color(255, 255, 255));
        lblInst1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst1.setText("A revolutionary new technology that prevents you from spending hours deciding what movie to watch!");
        lblInst1.setOpaque(true);

        lblInst2.setBackground(new java.awt.Color(51, 51, 51));
        lblInst2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInst2.setForeground(new java.awt.Color(255, 255, 255));
        lblInst2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst2.setText("After selecting your prefered rating and clicking the button, you will be presented with four movies to choose from.");
        lblInst2.setOpaque(true);

        lblControl.setBackground(new java.awt.Color(51, 51, 51));

        lblRating.setBackground(new java.awt.Color(255, 255, 255));
        lblRating.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRating.setForeground(new java.awt.Color(255, 255, 255));
        lblRating.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRating.setText("Select the rating");

        cbxG.setForeground(new java.awt.Color(255, 255, 255));
        cbxG.setText("G");
        cbxG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGActionPerformed(evt);
            }
        });

        cbxPG.setForeground(new java.awt.Color(255, 255, 255));
        cbxPG.setText("PG");
        cbxPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPGActionPerformed(evt);
            }
        });

        cbxPG13.setForeground(new java.awt.Color(255, 255, 255));
        cbxPG13.setText("PG-13");
        cbxPG13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPG13ActionPerformed(evt);
            }
        });

        btnGenerateMovies.setBackground(new java.awt.Color(232, 0, 0));
        btnGenerateMovies.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerateMovies.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateMovies.setText("Generate Movies");
        btnGenerateMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateMoviesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblControlLayout = new javax.swing.GroupLayout(lblControl);
        lblControl.setLayout(lblControlLayout);
        lblControlLayout.setHorizontalGroup(
            lblControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblControlLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(lblControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(lblControlLayout.createSequentialGroup()
                        .addComponent(cbxG, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxPG, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxPG13))
                    .addComponent(lblRating, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerateMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        lblControlLayout.setVerticalGroup(
            lblControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblControlLayout.createSequentialGroup()
                        .addComponent(btnGenerateMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(lblControlLayout.createSequentialGroup()
                        .addComponent(lblRating)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(lblControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxG)
                            .addComponent(cbxPG)
                            .addComponent(cbxPG13))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInst1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMovie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                    .addComponent(lblInst2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInst1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInst2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateMoviesActionPerformed
        // TODO add your handling code here:
        
        // Constants
        final String [][] gMovies = {
            {"Canvas", "/g/canvas.jpeg", "https://netflix.com/title/81332733", "G"},
            {"Charlotte's Web", "/g/charlottesWeb.jpg", "https://netflix.com/cx/title/70041962", "G"},
            {"Farmageddon", "/g/farmageddon.jpg", "https://netflix.com/title/80242602", "G"},
            {"Jungle Beat: The Movie", "/g/jungleBeat.jpeg", "https://netflix.com/title/81381727", "G"},
            {"The Magic Roundabout", "/g/magicRoundabout.jpeg", "https://netflix.com/title/70042691", "G"},
            {"Megamind", "/g/megamind.jpg", "https://netflix.com/title/70120612", "G"},
            {"Pup Star: World Tour", "/g/pupStar.jpg", "https://netflix.com/title/80189866", "G"},
            {"Robin Robin", "/g/robinRobin.jpeg", "https://netflix.com/title/81058433", "G"},
            {"Spookley the Square Pumpkin", "/g/spookley.jpg", "https://netflix.com/title/81141689", "G"},
        };
        
        final String [][] pgMovies = {
            {"Ballerina", "/pg/ballerina.jpg", "https://netflix.com/rs/title/80166318", "PG"},
            {"Chocolat", "/pg/chocolat.jpg", "https://netflix.com/sm-en/title/60003116", "PG"},
            {"Monty Python and the Holy Grail", "/pg/holyGrail.jpg", "https://netflix.com/title/771476", "PG"},
            {"Klaus", "/pg/klaus.jpg", "https://netflix.com/title/80183187", "PG"},
            {"Knock Down The House", "/pg/knockDownTheHouse.jpg", "https://netflix.com/title/81080637", "PG"},
            {"Lady Driver", "/pg/ladyDriver.jpg", "https://netflix.com/title/81271257", "PG"},
            {"The Short Game", "/pg/shortGame.jpg", "https://netflix.com/title/70290567", "PG"},
        };
        
        final String [][] pg13Movies = {
            {"Athlete A", "/pg13/athleteA.jpg", "https://netflix.com/title/81034185", "PG-13"},
            {"Blood Diamond", "/pg13/bloodDiamond.jpg", "https://netflix.com/title/70045850", "PG-13"},
            {"Coach Carter", "/pg13/coachCarter.jpg", "https://netflix.com/sm-en/title/70019004", "PG-13"},
            {"Eurovision Song Contest", "/pg13/eurovisionSongContest.jpg", "https://netflix.com/title/80244088", "PG-13"},
            {"Hachi: A Dog's Tale", "/pg13/hachi.jpg", "https://netflix.com/title/70118677", "PG-13"},
            {"The Imitation Game", "/pg13/imitationGame.jpg", "https://netflix.com/title/70295172", "PG-13"},
            {"A Monster Calls", "/pg13/monsterCalls.jpeg", "https://netflix.com/title/80022607", "PG-13"},
            {"Seven Pounds", "/pg13/sevenPounds.jpg", "https://netflix.com/title/70104313", "PG-13"},
            {"Snatch", "/pg13/snatch.jpg", "https://netflix.com/am/title/60003388", "PG-13"},
            {"The Two Popes", "/pg13/twoPopes.jpg", "https://netflix.com/title/80174451", "PG-13"},
            {"Undefeated", "/pg13/undefeated.jpg", "https://netflix.com/title/70177633", "PG-13"}      
        };
        
        // Variables
        String [][] movieChoices = {};
        
        String [] movieTitle = new String [4];
        String [] movieImage = new String [4];
        String [] movieRating = new String [4];
        
       
        
        
        // Make sure the user has selected a rating before proceeding
        if (!(cbxG.isSelected()) && !(cbxPG.isSelected()) && !(cbxPG13.isSelected())) {
            // Indicate that the user needs to select a rating
            cbxG.requestFocus();

            // exit
            return;
        }
        
        // Add G rated movies to the possible movie choices
        if (cbxG.isSelected()) {
            movieChoices = new String [gMovies.length][4];
            System.arraycopy(gMovies, 0, movieChoices, 0, movieChoices.length);
        }
        
        // Add PG rated movies to the possible movie choices
        if (cbxPG.isSelected()) {
            movieChoices = append(pgMovies, movieChoices);
        }

        // Add PG-13 rated movies to the possible movie choices
        if (cbxPG13.isSelected()) {
            movieChoices = append(pg13Movies, movieChoices);
        }
        
        // Select four random movies from the possible movie choices
        for (int i = 0; i < 4; i ++) {
            int randomPos;
            do {
                randomPos = (int)Math.round(Math.random() * (movieChoices.length - 1));
            } while (isIn(movieChoices[randomPos][0], movieTitle));
            // Assign variables for each movie
            movieTitle[i] = movieChoices[randomPos][0];
            movieImage[i] = movieChoices[randomPos][1];
            movieLink[i] = movieChoices[randomPos][2];
            movieRating[i] = movieChoices[randomPos][3];
        }
        
        // Output all the movie posters
        lblPoster1.setIcon(new javax.swing.ImageIcon(getClass().getResource(movieImage[0])));
        lblPoster2.setIcon(new javax.swing.ImageIcon(getClass().getResource(movieImage[1])));
        lblPoster3.setIcon(new javax.swing.ImageIcon(getClass().getResource(movieImage[2])));
        lblPoster4.setIcon(new javax.swing.ImageIcon(getClass().getResource(movieImage[3])));
        
        // Output the movie names
        lblMovie1.setText(movieTitle[0]);
        lblMovie2.setText(movieTitle[1]);
        lblMovie3.setText(movieTitle[2]);
        lblMovie4.setText(movieTitle[3]);
        
        // Output the movie ratings
        lblRating1.setText(movieRating[0]);
        lblRating2.setText(movieRating[1]);
        lblRating3.setText(movieRating[2]);
        lblRating4.setText(movieRating[3]);
        
        // After being clicked, disable this button and the rating checkboxes
        btnGenerateMovies.setEnabled(false);
        cbxG.setEnabled(false);
        cbxPG.setEnabled(false);
        cbxPG13.setEnabled(false);
    }//GEN-LAST:event_btnGenerateMoviesActionPerformed

    private void btnWatch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWatch1ActionPerformed
        // TODO add your handling code here:

        // Open the link to the Netflix movie
        try {
            Desktop.getDesktop().browse(new URL(movieLink[0]).toURI());
        } catch (Exception e) {
           System.out.println("Error: \"" + e + "\".");
        }
    }//GEN-LAST:event_btnWatch1ActionPerformed

    private void btnWatch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWatch2ActionPerformed
        // TODO add your handling code here:

        // Open the link to the Netflix movie
        try {
            Desktop.getDesktop().browse(new URL(movieLink[1]).toURI());
        } catch (Exception e) {
           System.out.println("Error: \"" + e + "\".");
        }
    }//GEN-LAST:event_btnWatch2ActionPerformed

    private void btnWatch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWatch3ActionPerformed
        // TODO add your handling code here:

        // Open the link to the Netflix movie
        try {
            Desktop.getDesktop().browse(new URL(movieLink[2]).toURI());
        } catch (Exception e) {
           System.out.println("Error: \"" + e + "\".");
        }
    }//GEN-LAST:event_btnWatch3ActionPerformed

    private void btnWatch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWatch4ActionPerformed
        // TODO add your handling code here:

        // Open the link to the Netflix movie
        try {
            Desktop.getDesktop().browse(new URL(movieLink[3]).toURI());
        } catch (Exception e) {
           System.out.println("Error: \"" + e + "\".");
        }
    }//GEN-LAST:event_btnWatch4ActionPerformed

    private void cbxGActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }
                                        

    private void cbxPGActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                     

    private void cbxPG13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNetflixShowSelectorJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNetflixShowSelectorJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNetflixShowSelectorJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNetflixShowSelectorJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNetflixShowSelectorJW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateMovies;
    private javax.swing.JButton btnWatch1;
    private javax.swing.JButton btnWatch2;
    private javax.swing.JButton btnWatch3;
    private javax.swing.JButton btnWatch4;
    private javax.swing.JCheckBox cbxG;
    private javax.swing.JCheckBox cbxPG;
    private javax.swing.JCheckBox cbxPG13;
    private javax.swing.JPanel lblControl;
    private javax.swing.JLabel lblInst1;
    private javax.swing.JLabel lblInst2;
    private javax.swing.JLabel lblMovie1;
    private javax.swing.JLabel lblMovie2;
    private javax.swing.JLabel lblMovie3;
    private javax.swing.JLabel lblMovie4;
    private javax.swing.JLabel lblPoster1;
    private javax.swing.JLabel lblPoster2;
    private javax.swing.JLabel lblPoster3;
    private javax.swing.JLabel lblPoster4;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblRating1;
    private javax.swing.JLabel lblRating2;
    private javax.swing.JLabel lblRating3;
    private javax.swing.JLabel lblRating4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlMovie;
    // End of variables declaration//GEN-END:variables
}
