/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jijwa
 */
public class FrmDiceGuessingGameJW extends javax.swing.JFrame {

    // Global Variables
    int totalRolls = 0;
    int totalCorrect = 0;
    int totalIncorrect = 0;
    double percentCorrect = 0;
    
    int diceGuess;
    
    // Global Constants
    final String DICE_FACES[] = {"/dice1.png", "/dice2.png", "/dice3.png", "/dice4.png", "/dice5.png", "/dice6.png"};
    
    /**
     * Creates new form FrmDiceGuessingGameJW
     */
    public FrmDiceGuessingGameJW() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRolls = new javax.swing.JPanel();
        pnlDiceRoll = new javax.swing.JPanel();
        lblDiceRoll = new javax.swing.JLabel();
        btnRollDice = new javax.swing.JButton();
        pnlUserGuess = new javax.swing.JPanel();
        sldUserGuess = new javax.swing.JSlider();
        lblUserGuess = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblInst2 = new javax.swing.JLabel();
        lblInst1 = new javax.swing.JLabel();
        lblRollsValue = new javax.swing.JLabel();
        lblRolls = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblCorrectValue = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        lblPercent = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRolls.setBackground(new java.awt.Color(255, 255, 255));
        pnlRolls.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        pnlDiceRoll.setBackground(new java.awt.Color(255, 255, 255));
        pnlDiceRoll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlDiceRoll.setPreferredSize(new java.awt.Dimension(130, 138));

        lblDiceRoll.setBackground(new java.awt.Color(255, 255, 255));
        lblDiceRoll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice3.png"))); // NOI18N
        lblDiceRoll.setOpaque(true);

        javax.swing.GroupLayout pnlDiceRollLayout = new javax.swing.GroupLayout(pnlDiceRoll);
        pnlDiceRoll.setLayout(pnlDiceRollLayout);
        pnlDiceRollLayout.setHorizontalGroup(
            pnlDiceRollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiceRollLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDiceRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlDiceRollLayout.setVerticalGroup(
            pnlDiceRollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDiceRollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDiceRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnRollDice.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        btnRollDice.setText("Roll the Dice");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        pnlUserGuess.setBackground(new java.awt.Color(255, 255, 255));
        pnlUserGuess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUserGuess.setPreferredSize(new java.awt.Dimension(130, 138));

        sldUserGuess.setMaximum(5);
        sldUserGuess.setValue(2);
        sldUserGuess.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sldUserGuessMouseDragged(evt);
            }
        });

        lblUserGuess.setBackground(new java.awt.Color(255, 255, 255));
        lblUserGuess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice3.png"))); // NOI18N
        lblUserGuess.setText("jLabel1");
        lblUserGuess.setOpaque(true);

        javax.swing.GroupLayout pnlUserGuessLayout = new javax.swing.GroupLayout(pnlUserGuess);
        pnlUserGuess.setLayout(pnlUserGuessLayout);
        pnlUserGuessLayout.setHorizontalGroup(
            pnlUserGuessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserGuessLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlUserGuessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlUserGuessLayout.setVerticalGroup(
            pnlUserGuessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserGuessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserGuess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlRollsLayout = new javax.swing.GroupLayout(pnlRolls);
        pnlRolls.setLayout(pnlRollsLayout);
        pnlRollsLayout.setHorizontalGroup(
            pnlRollsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRollsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRollsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRollsLayout.createSequentialGroup()
                        .addComponent(pnlUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlDiceRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRollDice, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlRollsLayout.setVerticalGroup(
            pnlRollsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRollsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRollsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDiceRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRollDice)
                .addContainerGap())
        );

        lblHeader.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Dice Guesing Game of Amazingness");

        lblInst2.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        lblInst2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst2.setText("Roll the dice to test your luck");

        lblInst1.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        lblInst1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInst1.setText("Select the dice face that you think will come up");

        lblRollsValue.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lblRollsValue.setText("0");

        lblRolls.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lblRolls.setText("Total Rolls:");
        lblRolls.setPreferredSize(new java.awt.Dimension(100, 21));

        lblCorrect.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lblCorrect.setText("Correct Rolls:");
        lblCorrect.setMaximumSize(new java.awt.Dimension(100, 21));
        lblCorrect.setMinimumSize(new java.awt.Dimension(100, 21));
        lblCorrect.setName(""); // NOI18N
        lblCorrect.setPreferredSize(new java.awt.Dimension(100, 21));

        lblCorrectValue.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lblCorrectValue.setText("0");

        lblPercentValue.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lblPercentValue.setText("0");

        lblIncorrect.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lblIncorrect.setText("Incorrect Rolls:");

        lblPercent.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lblPercent.setText("Correct Roll %:");

        lblIncorrectValue.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lblIncorrectValue.setText("0");

        lblMessage.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInst1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblInst2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCorrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRolls, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRollsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorrectValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIncorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIncorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPercentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlRolls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addComponent(lblInst1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInst2)
                .addGap(24, 24, 24)
                .addComponent(pnlRolls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRollsValue)
                    .addComponent(lblRolls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPercent)
                    .addComponent(lblPercentValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCorrectValue)
                        .addComponent(lblCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIncorrect)
                        .addComponent(lblIncorrectValue)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldUserGuessMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldUserGuessMouseDragged
        // TODO add your handling code here:
        
        // Variables
        String diceFace;
             
        // Get the users guess
        diceGuess = sldUserGuess.getValue();
        
        // Get the image of the dice face
        diceFace = DICE_FACES[diceGuess];

        // Output the image
        lblUserGuess.setIcon(new javax.swing.ImageIcon(getClass().getResource(diceFace)));
        
        // Reset any colouration or images shown by the dice roll label
        lblDiceRoll.setIcon(null);
        lblDiceRoll.setBackground(new java.awt.Color(255, 255, 255));
        lblUserGuess.setBackground(new java.awt.Color(255, 255, 255));
        
    }//GEN-LAST:event_sldUserGuessMouseDragged

    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
        // TODO add your handling code here:
        
        // Variables
        int diceRoll = (int)Math.round(Math.random()*5); // Random number from 0 - 5
        String diceFace;
        
        // get the image for the random roll
        diceFace = DICE_FACES[diceRoll];
        
        // Output the image
        lblDiceRoll.setIcon(new javax.swing.ImageIcon(getClass().getResource(diceFace)));
        
        // Determine if the user guessed correctly
        if (diceGuess == diceRoll)
        {   
            // Set the background to green
            lblDiceRoll.setBackground(new java.awt.Color(10, 200, 10));
            lblUserGuess.setBackground(new java.awt.Color(10, 200, 10));
            
            // Increase the number of correct guesses
            totalCorrect ++;
        }
        else
        {
            // Set the background to red
            lblDiceRoll.setBackground(new java.awt.Color(200, 0, 0));
            lblUserGuess.setBackground(new java.awt.Color(200, 10, 10));
            
            // Increase the number of incorrect guesses
            totalIncorrect ++;
        }
        
        // Increase the number of total rolls
        totalRolls ++;
        
        // Calculate the percent correct
        percentCorrect = (double)totalCorrect/(double)totalRolls * 100;
        
        // Output a message if the user is lucky or unlucky, but only after the 5th round
        if ((percentCorrect > 22) && (totalRolls > 5))
        {
            lblMessage.setText("Lucky!");
        }
        else if ((percentCorrect < 10) && (totalRolls > 5))
        {
            lblMessage.setText("Unlucky!");
        }
        else
        {
            lblMessage.setText("");
        }
        
        // Ouput the statistics
        lblRollsValue.setText(String.valueOf(totalRolls));
        lblCorrectValue.setText(String.valueOf(totalCorrect));
        lblIncorrectValue.setText(String.valueOf(totalIncorrect));
        lblPercentValue.setText(String.valueOf(percentCorrect)+"%");
        
        
    }//GEN-LAST:event_btnRollDiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGuessingGameJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGuessingGameJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGuessingGameJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGuessingGameJW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDiceGuessingGameJW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRollDice;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblDiceRoll;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblInst1;
    private javax.swing.JLabel lblInst2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblRolls;
    private javax.swing.JLabel lblRollsValue;
    private javax.swing.JLabel lblUserGuess;
    private javax.swing.JPanel pnlDiceRoll;
    private javax.swing.JPanel pnlRolls;
    private javax.swing.JPanel pnlUserGuess;
    private javax.swing.JSlider sldUserGuess;
    // End of variables declaration//GEN-END:variables
}
